<?php

use PHPUnit\Framework\TestCase;
use Dykyi\Common\Config;

class ServiceTest extends TestCase
{
    private $pusherConfig = [];

    public function __construct()
    {
        $dotenv = new \Dotenv\Dotenv(__DIR__);
        $dotenv->load();

        parent::__construct();
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->pusherConfig =
            ['auth_key' => Config::env('PUSHER_KEY'),
            'secret'   => Config::env('PUSHER_SECRET'),
            'app_id'   => Config::env('PUSHER_APP_ID'),
            'options'  => ['encrypted' => true],
        ];
    }

    public function testPusher()
    {
        $pusher  = new \Dykyi\Services\Push\PushClass($this->pusherConfig);
        $factory = new \Dykyi\Services\Push\PushFactory($pusher);
        $result  = $factory->send([
            'user' => [
                'id'   => 0,
                'name' => 'test',]], 'test-event'
        );
        $this->assertTrue($result);

    }
}
